# Generated by Django 5.1.7 on 2026-06-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My CV', max_length=100)),
                ('cv_file', models.FileField(help_text='Upload .docx or .doc files only', upload_to='cv_uploads/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
