# Generated by Django 5.1.7 on 2026-06-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Documentation', max_length=255)),
                ('file', models.FileField(help_text='Upload .pdf, .docx, or .doc files only', upload_to='documentation_uploads/')),
            ],
        ),
    ]
