# Generated by Django 5.1.7 on 2026-06-22 11:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_documentation'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentation',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
